### ISSUE TITLE
Error when adding to project: `Value of type 'CALayer' has no member 'proxy'`

### ISSUE THREAD

**Issue by heyjaywilson** [benlmyers/swiftui-particles#5]
I added `ParticlesPresets` to a project to try, but it seems to not compile due to `Value of type 'CALayer' has no member 'proxy'`. The dependency is pointed to the main branch and I'm trying to build for iOS.

**Comment by benlmyers** [comment]
Will look into your issue! Thanks for reporting!

**Comment by benlmyers** [comment]
Hi @heyjaywilson,

I pushed a build fix that should allow Particles to compile for iOS. Sadly I had to remove Lattice functionality for iOS and will identify the issue tomorrow. Sorry for the trouble!

**Comment by heyjaywilson** [comment]
All good! Thanks for the update. Still excited to give this a try!
